version: '3'
services:
  langchain:
    build:
      dockerfile: libs/langchain/dev.Dockerfile
      context: ..
    volumes:
      - .:/workspace
    networks:
      - langchain-network

networks:
  langchain-network:
    driver: bridge
